/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Publisher.SSPManagerRole;

import Business.Customer.Customer;
import Business.Publisher.AdSpace.AdSpace;
import Business.Publisher.ServerSidePlatform.SSP;
import Business.Publisher.ServerSidePlatform.SSPDirectory;
import Business.Utils.MyDoubleVerifier;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sonam
 */
public class AddSSPJPanel extends javax.swing.JPanel {

    /**
     * Creates new form addDSPJPanel
     */
    private JPanel userProcessContainer;
    private SSPDirectory sspDirectory;
    private AdSpace adSpace;
    public AddSSPJPanel(JPanel userProcessContainer,SSPDirectory sspDirectory,AdSpace adSpace) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.sspDirectory= sspDirectory;
        this.adSpace=adSpace;
        setVerifiers();
        populateComboboxes();
    }

    private void setVerifiers()
    {
        MyDoubleVerifier myDoubleVerifier= new MyDoubleVerifier();
        basePriceJTextField.setInputVerifier(myDoubleVerifier);
    }
    private void populateComboboxes()
    {
        genderJComboBox.removeAllItems();;
        ageRangeJComboBox.removeAllItems();
        incomeRangeJComboBox.removeAllItems();;
        occupationJComboBox.removeAllItems();
        
        
        for(Customer.Gender gender: Customer.Gender.values())
        {
            
                genderJComboBox.addItem(gender);
            
        }
        
        for(Customer.AgeRange ageRange: Customer.AgeRange.values())
        {
            
                ageRangeJComboBox.addItem(ageRange);
            
        }
        
        for(Customer.IncomeRange incomeRange: Customer.IncomeRange.values())
        {
            
                incomeRangeJComboBox.addItem(incomeRange);
            
        }
        
        for(Customer.Occupation occupation: Customer.Occupation.values())
        {
            
                occupationJComboBox.addItem(occupation);
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        genderJComboBox = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        ageRangeJComboBox = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        occupationJComboBox = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        incomeRangeJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        basePriceJTextField = new javax.swing.JTextField();
        backJButton1 = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        jLabel12.setText("Gender:");

        jLabel13.setText("Age Range:");

        jLabel14.setText("Occupation:");

        jLabel15.setText("Income Range:");

        jLabel1.setText("Base Price:");

        backJButton1.setText("<<Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });

        saveJButton.setText("Save");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Add SSP Rule");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(backJButton1))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveJButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ageRangeJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(genderJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(occupationJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(incomeRangeJComboBox, 0, 150, Short.MAX_VALUE)
                                .addComponent(basePriceJTextField)))))
                .addContainerGap(572, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(genderJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ageRangeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(occupationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(incomeRangeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(basePriceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton1)
                    .addComponent(saveJButton))
                .addContainerGap(410, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed

    private Boolean validateFields()
    {
        if(genderJComboBox.getSelectedIndex()==-1
            || occupationJComboBox.getSelectedIndex()==-1
                || incomeRangeJComboBox.getSelectedIndex()==-1
                || ageRangeJComboBox.getSelectedIndex()==-1
                || basePriceJTextField.getText().length()==0)
        {
            return false;
        }
        return true;
    }
    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:
        if(!validateFields())
        {
            JOptionPane.showMessageDialog(this,"Please enter correct fields","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        SSP ssp= sspDirectory.createAndAddSSP();
        ssp.setAdSpace(adSpace);
        
        Customer.Gender gender= (Customer.Gender) genderJComboBox.getSelectedItem();
        ssp.setGender(gender);
        
        Customer.AgeRange ageRange=(Customer.AgeRange) ageRangeJComboBox.getSelectedItem();
        ssp.setAgeRange(ageRange);
        
        Customer.IncomeRange incomeRange= (Customer.IncomeRange) incomeRangeJComboBox.getSelectedItem();
        ssp.setIncomeRange(incomeRange);
        
        Customer.Occupation occupation= (Customer.Occupation) occupationJComboBox.getSelectedItem();
        ssp.setOccupation(occupation);
        
        ssp.setBasePrice(Double.parseDouble(basePriceJTextField.getText()));
        ssp.setEnabled(true);
        JOptionPane.showMessageDialog(this,"SSP added!!","Update",JOptionPane.INFORMATION_MESSAGE);
        //Clearing all values;
        populateComboboxes();
        basePriceJTextField.setText("");
    }//GEN-LAST:event_saveJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ageRangeJComboBox;
    private javax.swing.JButton backJButton1;
    private javax.swing.JTextField basePriceJTextField;
    private javax.swing.JComboBox genderJComboBox;
    private javax.swing.JComboBox incomeRangeJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JComboBox occupationJComboBox;
    private javax.swing.JButton saveJButton;
    // End of variables declaration//GEN-END:variables
}
