/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Publisher.SSPManagerRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PublisherEnterprise;
import Business.Publisher.AdSpace.AdSpace;
import Business.Publisher.ServerSidePlatform.SSP;
import UserInterface.Publisher.AdSpaceManagerRole.ViewEditAdSpaceDetailsJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sonam
 */
public class SSPManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DSPManagerJPanel
     */
    private JPanel userProcessContainer;
    private PublisherEnterprise publisherEnterprise;

    public SSPManagerWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.publisherEnterprise = (PublisherEnterprise) enterprise;
        populateAdSpaceInventory();
        populateSSPs(null);
    }

    private void populateAdSpaceInventory()
    {
        DefaultTableModel dtm= (DefaultTableModel) adSpaceInventoryJTable.getModel();
        dtm.setRowCount(0);

        for (AdSpace adSpace : publisherEnterprise.getAdSpaceInventory().getAdSpaceList()) {
            if (adSpace.isReady()) 
            {
                Object row[] = new Object[5];

                row[0] = adSpace.getAdSpaceID();
                row[1] = adSpace;
                row[2] = adSpace.getDateCreated();
                row[3] = adSpace.isEnabled()== Boolean.TRUE ?  "Yes":"No";
                row[4] = adSpace.getNotes();
                dtm.addRow(row);
            }
        }
    }

    private void populateSSPs(AdSpace adSpace) {
        DefaultTableModel dtm = (DefaultTableModel) sspsJTable.getModel();
        dtm.setRowCount(0);

        for (SSP ssp : publisherEnterprise.getSSPDirectory().getSspList()) {
            if(ssp.getAdSpace()==adSpace)
            {
                Object row[] = new Object[7];

                row[0] = ssp;
                row[1] = ssp.getAgeRange().getValue();
                row[2] = ssp.getOccupation().getValue();
                row[3] = ssp.getIncomeRange().getValue();
                row[4] = ssp.getGender().getValue();
                row[5] = ssp.getBasePrice();
                row[6] = ssp.isEnabled() == Boolean.TRUE ? "Yes" : "No";

                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewSSPsJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sspsJTable = new javax.swing.JTable();
        addSSPJButton = new javax.swing.JButton();
        editSSPJButton = new javax.swing.JButton();
        removeSSPJButton = new javax.swing.JButton();
        enableDisableSSPJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        adSpaceInventoryJTable = new javax.swing.JTable();
        viewAdSpaceDetailsJButton1 = new javax.swing.JButton();
        refreshAllJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SSP Manager Work Area");

        viewSSPsJButton.setText("View SSP's");
        viewSSPsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSSPsJButtonActionPerformed(evt);
            }
        });

        sspsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "SSP ID", "Age Range", "Occupation", "Income Range", "Gender", "Cost Per Click", "Enabled?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(sspsJTable);

        addSSPJButton.setText("Add SSP");
        addSSPJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSSPJButtonActionPerformed(evt);
            }
        });

        editSSPJButton.setText("Edit SSP");
        editSSPJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSSPJButtonActionPerformed(evt);
            }
        });

        removeSSPJButton.setText("Remove SSP");
        removeSSPJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSSPJButtonActionPerformed(evt);
            }
        });

        enableDisableSSPJButton.setText("Enable/Disable SSP");
        enableDisableSSPJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableDisableSSPJButtonActionPerformed(evt);
            }
        });

        adSpaceInventoryJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ad Space ID", "Title", "Date Created", "Enabled?", "Notes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(adSpaceInventoryJTable);

        viewAdSpaceDetailsJButton1.setText("View Ad Space Detils");
        viewAdSpaceDetailsJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAdSpaceDetailsJButton1ActionPerformed(evt);
            }
        });

        refreshAllJButton.setText("Refresh All");
        refreshAllJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshAllJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editSSPJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeSSPJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enableDisableSSPJButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewSSPsJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addSSPJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewAdSpaceDetailsJButton1))
                    .addComponent(refreshAllJButton)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshAllJButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewSSPsJButton)
                    .addComponent(addSSPJButton)
                    .addComponent(viewAdSpaceDetailsJButton1))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editSSPJButton)
                    .addComponent(removeSSPJButton)
                    .addComponent(enableDisableSSPJButton))
                .addContainerGap(455, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewSSPsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSSPsJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = adSpaceInventoryJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an Ad Space.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        AdSpace adSpace = (AdSpace) adSpaceInventoryJTable.getValueAt(selectedRow, 1);
        
        populateSSPs(adSpace);
    }//GEN-LAST:event_viewSSPsJButtonActionPerformed

    private void addSSPJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSSPJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = adSpaceInventoryJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an Ad Space.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        AdSpace adSpace = (AdSpace) adSpaceInventoryJTable.getValueAt(selectedRow, 1);

        AddSSPJPanel asspjp = new AddSSPJPanel(userProcessContainer,publisherEnterprise.getSSPDirectory(), adSpace);
        userProcessContainer.add("AddSSPJPanel", asspjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addSSPJButtonActionPerformed

    private void editSSPJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSSPJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = sspsJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a SSP.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        SSP ssp= (SSP) sspsJTable.getValueAt(selectedRow, 0);
        
        EditSSPJPanel esspjp = new EditSSPJPanel(userProcessContainer, ssp);
        userProcessContainer.add("EditSSPJPanel", esspjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_editSSPJButtonActionPerformed

    private void removeSSPJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSSPJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = sspsJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a SSP.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        SSP ssp= (SSP) sspsJTable.getValueAt(selectedRow, 0);
        AdSpace adSpace= ssp.getAdSpace();
        publisherEnterprise.getAdSpaceInventory().removeAdpace(adSpace);
        System.out.println("SSP removed");
        JOptionPane.showMessageDialog(this, "SSP removed.", "Update", JOptionPane.INFORMATION_MESSAGE);
        populateSSPs(ssp.getAdSpace());
    }//GEN-LAST:event_removeSSPJButtonActionPerformed

    private void enableDisableSSPJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableDisableSSPJButtonActionPerformed
        // TODO add your handling code here:
        int flag;
        int selectedRow = sspsJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a SSP.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        SSP ssp= (SSP) sspsJTable.getValueAt(selectedRow, 0);
        
        if(ssp.isEnabled()==true)
        {
            flag = JOptionPane.showConfirmDialog(this, "Are you sure want to disable this SSP?", "Warning", JOptionPane.YES_NO_OPTION);
            if (flag == JOptionPane.YES_OPTION) {
                ssp.setEnabled(false);
                System.out.println("SSP disabled");
            }
        }else if(ssp.isEnabled()==false)
        {
            flag = JOptionPane.showConfirmDialog(this, "Are you sure want to enable this SSP?", "Warning", JOptionPane.YES_NO_OPTION);
            if (flag == JOptionPane.YES_OPTION) {
                ssp.setEnabled(true);
                System.out.println("SSP enabled");
            }
        }
        populateSSPs(ssp.getAdSpace());
    }//GEN-LAST:event_enableDisableSSPJButtonActionPerformed

    private void viewAdSpaceDetailsJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAdSpaceDetailsJButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = adSpaceInventoryJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an Ad Space.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        AdSpace adSpace= (AdSpace) adSpaceInventoryJTable.getValueAt(selectedRow, 1);

        ViewEditAdSpaceDetailsJPanel vasdjp = new ViewEditAdSpaceDetailsJPanel(userProcessContainer,adSpace);
        userProcessContainer.add("ViewAdSpaceDetailsJPanel", vasdjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_viewAdSpaceDetailsJButton1ActionPerformed

    private void refreshAllJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshAllJButtonActionPerformed
        // TODO add your handling code here:
        populateAdSpaceInventory();
        populateSSPs(null);
    }//GEN-LAST:event_refreshAllJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adSpaceInventoryJTable;
    private javax.swing.JButton addSSPJButton;
    private javax.swing.JButton editSSPJButton;
    private javax.swing.JButton enableDisableSSPJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshAllJButton;
    private javax.swing.JButton removeSSPJButton;
    private javax.swing.JTable sspsJTable;
    private javax.swing.JButton viewAdSpaceDetailsJButton1;
    private javax.swing.JButton viewSSPsJButton;
    // End of variables declaration//GEN-END:variables
}
