/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Advertiser.AdCreatorRole;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Advertiser.WorkRequests.AdCreationWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sonam
 */
public class AdCreatorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdCreatorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    private UserAccount userAccount;
    private String filePath;
    public AdCreatorWorkAreaJPanel(JPanel userProcessContainer,Organization organization,UserAccount userAccount,String filePath) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.organization=organization;
        this.userAccount=userAccount;
        this.filePath=filePath;
        populateOrgRequestsTable();
        populateMyRequestsTable();
    }

    private void populateOrgRequestsTable()
    {
        DefaultTableModel dtm= (DefaultTableModel) orgAdRequestsTable.getModel();
        dtm.setRowCount(0);

        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof AdCreationWorkRequest) {
                Object row[] = new Object[6];

                row[0] = request;
                row[1] = request.getSender();
                row[2] = request.getReceiver() == null ? null : request.getReceiver().getPerson().getName();
                row[3] = request.getStatus();
                row[4] = request.getRequestDate();
                row[5] = request.getResolveDate();
                dtm.addRow(row);
            }
        }
    }
    private void populateMyRequestsTable()
    {
        DefaultTableModel dtm= (DefaultTableModel) myAdRequestsTable.getModel();
        dtm.setRowCount(0);

        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof AdCreationWorkRequest && request.getReceiver()==userAccount) {
                Object row[] = new Object[6];

                row[0] = request;
                row[1] = request.getSender();
                row[2] = request.getReceiver() == null ? null : request.getReceiver().getPerson().getName();
                row[3] = request.getStatus();
                row[4] = request.getRequestDate();
                row[5] = request.getResolveDate();
                dtm.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orgAdRequestsTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        myAdRequestsTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        assignToMeJButton = new javax.swing.JButton();
        createEditAdJButton = new javax.swing.JButton();
        refreshAllJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ad Creator Work Area");

        jLabel2.setText("Organization Ad Requests:");

        orgAdRequestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status", "Request Date", "Resolve Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orgAdRequestsTable);

        myAdRequestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status", "Request Date", "Resolve Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(myAdRequestsTable);

        jLabel3.setText("My Requests:");

        assignToMeJButton.setText("Assign To Me");
        assignToMeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignToMeJButtonActionPerformed(evt);
            }
        });

        createEditAdJButton.setText("Create/Edit Ad");
        createEditAdJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEditAdJButtonActionPerformed(evt);
            }
        });

        refreshAllJButton.setText("Refresh All");
        refreshAllJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshAllJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(createEditAdJButton)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(refreshAllJButton)
                    .addComponent(assignToMeJButton))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshAllJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(assignToMeJButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createEditAdJButton)
                .addContainerGap(187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignToMeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignToMeJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = orgAdRequestsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Work Request.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        AdCreationWorkRequest myWorkRequest = (AdCreationWorkRequest) orgAdRequestsTable.getValueAt(selectedRow, 0);
        if(myWorkRequest.getReceiver()!=null)
        {
            JOptionPane.showMessageDialog(this, "Request is already assigned to "+myWorkRequest.getReceiver().getPerson().getName(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        myWorkRequest.setReceiver(userAccount);
        myWorkRequest.setStatus("Under Review");
        myWorkRequest.setResolveDate(new Date());
        System.out.println("Request assigned to "+userAccount.getUsername());
        populateOrgRequestsTable();
        populateMyRequestsTable();
    }//GEN-LAST:event_assignToMeJButtonActionPerformed

    private void createEditAdJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEditAdJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = myAdRequestsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Work Request.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        AdCreationWorkRequest myWorkRequest = (AdCreationWorkRequest) myAdRequestsTable.getValueAt(selectedRow, 0);
        ProcessAdCreationRequestJPanel piacrjp = new ProcessAdCreationRequestJPanel(userProcessContainer,myWorkRequest,filePath);
        userProcessContainer.add("ProcessImageAdCreationRequestJPanel", piacrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createEditAdJButtonActionPerformed

    private void refreshAllJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshAllJButtonActionPerformed
        // TODO add your handling code here:
        populateOrgRequestsTable();
        populateMyRequestsTable();
    }//GEN-LAST:event_refreshAllJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignToMeJButton;
    private javax.swing.JButton createEditAdJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable myAdRequestsTable;
    private javax.swing.JTable orgAdRequestsTable;
    private javax.swing.JButton refreshAllJButton;
    // End of variables declaration//GEN-END:variables
}
