/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerAdminRole;

import Business.Customer.Customer;
import Business.Customer.Customer.AgeRange;
import Business.Customer.Customer.Gender;
import Business.Customer.Customer.IncomeRange;
import Business.Customer.Customer.Occupation;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Utils.MyEmailVerifier;
import Business.Utils.MyPhoneNumberVerifier;
import Business.Utils.MyStringVerifier;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sonam
 */
public class AddCustomer extends javax.swing.JPanel {

    /**
     * Creates new form AddCustomer
     */
    private JPanel userProcessContainer;
    private OrganizationDirectory organizationDirectory;
    public AddCustomer(JPanel userProcessContainer,OrganizationDirectory organizationDirectory) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.organizationDirectory= organizationDirectory;
        setVerifiers();
        populateOrganizationComboBox();
        populateComboboxes();
    }
    private void setVerifiers()
    {
        MyStringVerifier myStringVerifier= new MyStringVerifier();
        customerNameJTextField.setInputVerifier(myStringVerifier);
        addressJTextField.setInputVerifier(myStringVerifier);
        cityJTextField.setInputVerifier(myStringVerifier);
        stateJTextField.setInputVerifier(myStringVerifier);
        countryJTextField.setInputVerifier(myStringVerifier);
        zipJTextField.setInputVerifier(myStringVerifier);
        MyEmailVerifier myEmailVerifier= new MyEmailVerifier();
        emailJTextField.setInputVerifier(myEmailVerifier);
        MyPhoneNumberVerifier myPhoneNumberVerifier= new MyPhoneNumberVerifier();
        phoneNumberJTextField.setInputVerifier(myPhoneNumberVerifier);
    }
    
    private void populateOrganizationComboBox()
    {
        organizationJComboBox.removeAllItems();
        //Populate Customer Organizations
        for(Organization o:organizationDirectory.getOrganizationList())
        {   
            if(o.getName().equals(Organization.Type.Customer.getValue()))
            {
                organizationJComboBox.addItem(o);
            }
        }
    }
    
    private void populateComboboxes()
    {
        genderJComboBox.removeAllItems();;
        ageRangeJComboBox.removeAllItems();
        incomeRangeJComboBox.removeAllItems();;
        occupationJComboBox.removeAllItems();
        
        for(Gender gender: Gender.values())
        {
            if(!gender.getValue().equals(Gender.Any.getValue()))
            {
                genderJComboBox.addItem(gender);
            }
        }
        
        for(AgeRange ageRange: AgeRange.values())
        {
            if(!ageRange.getValue().equals(AgeRange.Any.getValue()))
            {
                ageRangeJComboBox.addItem(ageRange);
            }
        }
        
        for(IncomeRange incomeRange: IncomeRange.values())
        {
            if(!incomeRange.getValue().equals(IncomeRange.Any.getValue()))
            {
                incomeRangeJComboBox.addItem(incomeRange);
            }
        }
        
        for(Occupation occupation: Customer.Occupation.values())
        {
            if(!occupation.getValue().equals(Occupation.Any.getValue()))
            {
                occupationJComboBox.addItem(occupation);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailJTextField = new javax.swing.JTextField();
        customerNameJTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        customerIDJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        phoneNumberJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        addCustomerJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        organizationJComboBox = new javax.swing.JComboBox();
        addressJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cityJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        stateJTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        countryJTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        zipJTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        genderJComboBox = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        ageRangeJComboBox = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        occupationJComboBox = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        incomeRangeJComboBox = new javax.swing.JComboBox();

        jLabel10.setText("Phone Number");

        customerIDJTextField.setEnabled(false);

        jLabel2.setText("Name");

        jLabel1.setText("Customer ID");

        jLabel3.setText("Address");

        jLabel8.setText("Email");

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        addCustomerJButton.setText("Add Customer");
        addCustomerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerJButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add Customer");

        jLabel5.setText("Organization");

        jLabel6.setText("City:");

        jLabel7.setText("State:");

        jLabel9.setText("Country:");

        jLabel11.setText("Zip:");

        jLabel12.setText("Gender:");

        jLabel13.setText("Age Range:");

        jLabel14.setText("Occupation:");

        jLabel15.setText("Income Range:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(customerNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ageRangeJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(genderJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(zipJTextField)
                                    .addComponent(addressJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(cityJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(stateJTextField)
                                    .addComponent(countryJTextField)
                                    .addComponent(occupationJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(incomeRangeJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(55, 55, 55)
                                    .addComponent(customerIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel5)
                                        .addComponent(backJButton))
                                    .addGap(55, 55, 55)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addCustomerJButton)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(phoneNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(organizationJComboBox, 0, 293, Short.MAX_VALUE)))))
                            .addComponent(jLabel15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                        .addContainerGap(503, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(customerIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customerNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addressJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(stateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(countryJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(zipJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(genderJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ageRangeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(occupationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(incomeRangeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(phoneNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(organizationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(addCustomerJButton))
                .addContainerGap(217, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private Boolean validateFields()
    {
        if(genderJComboBox.getSelectedIndex()==-1
            || occupationJComboBox.getSelectedIndex()==-1
                || incomeRangeJComboBox.getSelectedIndex()==-1
                || ageRangeJComboBox.getSelectedIndex()==-1
                || customerNameJTextField.getText().length()==0
                || addressJTextField.getText().length()==0
                || cityJTextField.getText().length()==0
                || stateJTextField.getText().length()==0
                || countryJTextField.getText().length()==0
                || zipJTextField.getText().length()==0
                || emailJTextField.getText().length()==0
                || phoneNumberJTextField.getText().length()==0)
        {
            return false;
        }
        return true;
    }
    private void addCustomerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerJButtonActionPerformed
        // TODO add your handling code here:
        Organization org= (Organization) organizationJComboBox.getSelectedItem();
        
        if(org==null)
        {
            JOptionPane.showMessageDialog(this,"Please select an organization.","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!validateFields())
        {
            JOptionPane.showMessageDialog(this,"Please enter correct fields.","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        Customer customer=org.getPersonDirectory().createAndAddCustomer();
        customer.setName(customerNameJTextField.getText());
        customer.setAddress1(addressJTextField.getText());
        customer.setCity(cityJTextField.getText());
        customer.setState(stateJTextField.getText());
        customer.setCountry(countryJTextField.getText());
        customer.setZip(zipJTextField.getText());
        
        Gender gender= (Gender) genderJComboBox.getSelectedItem();
        customer.setGender(gender);
        
        AgeRange ageRange=(AgeRange) ageRangeJComboBox.getSelectedItem();
        customer.setAgeRange(ageRange);
        
        IncomeRange incomeRange= (IncomeRange) incomeRangeJComboBox.getSelectedItem();
        customer.setIncomeRange(incomeRange);
        
        Occupation occupation= (Occupation) occupationJComboBox.getSelectedItem();
        customer.setOccupation(occupation);
        
        customer.setCustomerEmail(emailJTextField.getText());
        customer.setPhoneNumber(phoneNumberJTextField.getText());
        JOptionPane.showMessageDialog(this,"Customer added.","Update",JOptionPane.INFORMATION_MESSAGE);
        System.out.println("Customer created and details updated");
        //clearing fields
        customerNameJTextField.setText("");
        addressJTextField.setText("");
        cityJTextField.setText("");
        stateJTextField.setText("");
        countryJTextField.setText("");
        zipJTextField.setText("");
        populateComboboxes();
        populateOrganizationComboBox();
        emailJTextField.setText("");
        phoneNumberJTextField.setText("");
        customerIDJTextField.setText("");
        
    }//GEN-LAST:event_addCustomerJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerJButton;
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JComboBox ageRangeJComboBox;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField cityJTextField;
    private javax.swing.JTextField countryJTextField;
    private javax.swing.JTextField customerIDJTextField;
    private javax.swing.JTextField customerNameJTextField;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JComboBox genderJComboBox;
    private javax.swing.JComboBox incomeRangeJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox occupationJComboBox;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JTextField phoneNumberJTextField;
    private javax.swing.JTextField stateJTextField;
    private javax.swing.JTextField zipJTextField;
    // End of variables declaration//GEN-END:variables
}
