/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerAdminRole;

import Business.Business.EcoSystem;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Sonam
 */
public class CustomerAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private OrganizationDirectory organizationDirectory;
    private EcoSystem ecoSystem;
    public CustomerAdminWorkAreaJPanel(JPanel userProcessContainer,OrganizationDirectory organizationDirectory,EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.organizationDirectory=organizationDirectory;
        this.ecoSystem=ecoSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageCustomersJButton = new javax.swing.JButton();
        manageUserAccountsJButton = new javax.swing.JButton();
        manageOrganizationsJButton = new javax.swing.JButton();
        viewBrowsingHistoryJButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        manageCustomersJButton.setText("Manage Customers");
        manageCustomersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomersJButtonActionPerformed(evt);
            }
        });

        manageUserAccountsJButton.setText("Manage User Accounts");
        manageUserAccountsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserAccountsJButtonActionPerformed(evt);
            }
        });

        manageOrganizationsJButton.setText("Manage Customer Organizations");
        manageOrganizationsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationsJButtonActionPerformed(evt);
            }
        });

        viewBrowsingHistoryJButton.setText("View Browsing History");
        viewBrowsingHistoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBrowsingHistoryJButtonActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Customer Admin Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(manageOrganizationsJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manageCustomersJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manageUserAccountsJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewBrowsingHistoryJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageOrganizationsJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageCustomersJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageUserAccountsJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewBrowsingHistoryJButton)
                .addContainerGap(403, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageOrganizationsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationsJButtonActionPerformed
        // TODO add your handling code here:
        ManageCustomerOrganizationsJPanel mcojp= new ManageCustomerOrganizationsJPanel(userProcessContainer,organizationDirectory);
        userProcessContainer.add("ManageCustomerOrganizationsJPanel", mcojp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationsJButtonActionPerformed

    private void manageCustomersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomersJButtonActionPerformed
        // TODO add your handling code here:
        ManageCustomers mcjp= new ManageCustomers(userProcessContainer,organizationDirectory);
        userProcessContainer.add("ManageCustomers", mcjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCustomersJButtonActionPerformed

    private void manageUserAccountsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserAccountsJButtonActionPerformed
        // TODO add your handling code here:
        ManageCustomerUserAccountsJPanel mcuajp= new ManageCustomerUserAccountsJPanel(userProcessContainer,organizationDirectory,ecoSystem);
        userProcessContainer.add("ManageCustomerUserAccountsJPanel", mcuajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageUserAccountsJButtonActionPerformed

    private void viewBrowsingHistoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBrowsingHistoryJButtonActionPerformed
        // TODO add your handling code here:
        ViewCustomerBrowsingHistoryJPanel vcbhjp= new ViewCustomerBrowsingHistoryJPanel(userProcessContainer,organizationDirectory,ecoSystem);
        userProcessContainer.add("ViewCustomerBrowsingHistoryJPanel", vcbhjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewBrowsingHistoryJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel16;
    private javax.swing.JButton manageCustomersJButton;
    private javax.swing.JButton manageOrganizationsJButton;
    private javax.swing.JButton manageUserAccountsJButton;
    private javax.swing.JButton viewBrowsingHistoryJButton;
    // End of variables declaration//GEN-END:variables
}
