/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerAdminRole;

import Business.Customer.Customer;
import Business.Utils.MyEmailVerifier;
import Business.Utils.MyPhoneNumberVerifier;
import Business.Utils.MyStringVerifier;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sonam
 */
public class ViewCustomerDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCustomerDetails
     */
    private JPanel userProcessContainer;
    private Customer customer;

    public ViewCustomerDetailsJPanel(JPanel userProcessContainer, Customer customer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customer = customer;
        setVerifiers();
        populateComboboxes();
        populateCustomerDetails();
    }
    private void setVerifiers()
    {
        MyStringVerifier myStringVerifier= new MyStringVerifier();
        customerNameJTextField.setInputVerifier(myStringVerifier);
        addressJTextField.setInputVerifier(myStringVerifier);
        cityJTextField.setInputVerifier(myStringVerifier);
        stateJTextField.setInputVerifier(myStringVerifier);
        countryJTextField.setInputVerifier(myStringVerifier);
        zipJTextField.setInputVerifier(myStringVerifier);
        MyEmailVerifier myEmailVerifier= new MyEmailVerifier();
        emailJTextField.setInputVerifier(myEmailVerifier);
        MyPhoneNumberVerifier myPhoneNumberVerifier= new MyPhoneNumberVerifier();
        phoneNumberJTextField.setInputVerifier(myPhoneNumberVerifier);
    }

    private void populateCustomerDetails() {
        customerIDJTextField.setText(String.valueOf(customer.getCustomerID()));
        customerNameJTextField.setText(customer.getName());
        addressJTextField.setText(customer.getAddress1());
        emailJTextField.setText(customer.getCustomerEmail());
        phoneNumberJTextField.setText(customer.getPhoneNumber());
        cityJTextField.setText(customer.getCity());
        stateJTextField.setText(customer.getState());
        countryJTextField.setText(customer.getCountry());
        zipJTextField.setText(customer.getZip());
        genderJComboBox.setSelectedItem(customer.getGender());
        ageRangeJComboBox.setSelectedItem(customer.getAgeRange());
        incomeRangeJComboBox.setSelectedItem(customer.getIncomeRange());
        occupationJComboBox.setSelectedItem(customer.getOccupation());
    }
    
     private void populateComboboxes()
    {
        genderJComboBox.removeAllItems();;
        ageRangeJComboBox.removeAllItems();
        incomeRangeJComboBox.removeAllItems();;
        occupationJComboBox.removeAllItems();
        
        for(Customer.Gender gender: Customer.Gender.values())
        {
            if(!gender.getValue().equals(Customer.Gender.Any.getValue()))
            {
                genderJComboBox.addItem(gender);
            }
        }
        
        for(Customer.AgeRange ageRange: Customer.AgeRange.values())
        {
            if(!ageRange.getValue().equals(Customer.AgeRange.Any.getValue()))
            {
                ageRangeJComboBox.addItem(ageRange);
            }
        }
        
        for(Customer.IncomeRange incomeRange: Customer.IncomeRange.values())
        {
            if(!incomeRange.getValue().equals(Customer.IncomeRange.Any.getValue()))
            {
                incomeRangeJComboBox.addItem(incomeRange);
            }
        }
        
        for(Customer.Occupation occupation: Customer.Occupation.values())
        {
            if(!occupation.getValue().equals(Customer.Occupation.Any.getValue()))
            {
                occupationJComboBox.addItem(occupation);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        customerIDJTextField = new javax.swing.JTextField();
        customerNameJTextField = new javax.swing.JTextField();
        emailJTextField = new javax.swing.JTextField();
        phoneNumberJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();
        updateJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        zipJTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cityJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        countryJTextField = new javax.swing.JTextField();
        stateJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        genderJComboBox = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        ageRangeJComboBox = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        occupationJComboBox = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        incomeRangeJComboBox = new javax.swing.JComboBox();
        addressJTextField = new javax.swing.JTextField();

        jLabel1.setText("Customer ID");

        jLabel2.setText("Name");

        jLabel3.setText("Address");

        jLabel8.setText("Email");

        jLabel10.setText("Phone Number");

        customerIDJTextField.setEnabled(false);

        customerNameJTextField.setEnabled(false);

        emailJTextField.setEnabled(false);

        phoneNumberJTextField.setEnabled(false);

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        saveJButton.setText("Save");
        saveJButton.setEnabled(false);
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });

        updateJButton.setText("Update");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("View Customer Details");

        jLabel12.setText("Gender:");

        zipJTextField.setEnabled(false);

        jLabel11.setText("Zip:");

        cityJTextField.setEnabled(false);

        jLabel7.setText("State:");

        jLabel9.setText("Country:");

        countryJTextField.setEnabled(false);

        stateJTextField.setEnabled(false);

        jLabel6.setText("City:");

        genderJComboBox.setEnabled(false);

        jLabel13.setText("Age Range:");

        ageRangeJComboBox.setEnabled(false);

        jLabel14.setText("Occupation:");

        occupationJComboBox.setEnabled(false);

        jLabel15.setText("Income Range:");

        incomeRangeJComboBox.setEnabled(false);

        addressJTextField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addGap(18, 18, 18)
                        .addComponent(saveJButton)
                        .addGap(18, 18, 18)
                        .addComponent(updateJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ageRangeJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(genderJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(zipJTextField)
                                .addComponent(addressJTextField)
                                .addComponent(cityJTextField)
                                .addComponent(stateJTextField)
                                .addComponent(countryJTextField)
                                .addComponent(occupationJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(incomeRangeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(customerIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(696, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageRangeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(occupationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(incomeRangeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(phoneNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(saveJButton)
                    .addComponent(updateJButton))
                .addContainerGap(265, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
        // TODO add your handling code here:
        customerNameJTextField.setEnabled(true);
        addressJTextField.setEnabled(true);
        cityJTextField.setEnabled(true);
        stateJTextField.setEnabled(true);
        countryJTextField.setEnabled(true);
        zipJTextField.setEnabled(true);
        genderJComboBox.setEnabled(true);
        ageRangeJComboBox.setEnabled(true);
        incomeRangeJComboBox.setEnabled(true);
        occupationJComboBox.setEnabled(true);
        emailJTextField.setEnabled(true);
        phoneNumberJTextField.setEnabled(true);

        updateJButton.setEnabled(false);
        saveJButton.setEnabled(true);
    }//GEN-LAST:event_updateJButtonActionPerformed

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:
        if(!validateFields())
        {
            JOptionPane.showMessageDialog(this,"Please enter correct fields.","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        customer.setName(customerNameJTextField.getText());
        customer.setAddress1(addressJTextField.getText());
        customer.setCity(cityJTextField.getText());
        customer.setState(stateJTextField.getText());
        customer.setCountry(countryJTextField.getText());
        customer.setZip(zipJTextField.getText());
        
        Customer.Gender gender= (Customer.Gender) genderJComboBox.getSelectedItem();
        customer.setGender(gender);
        
        Customer.AgeRange ageRange=(Customer.AgeRange) ageRangeJComboBox.getSelectedItem();
        customer.setAgeRange(ageRange);
        
        Customer.IncomeRange incomeRange= (Customer.IncomeRange) incomeRangeJComboBox.getSelectedItem();
        customer.setIncomeRange(incomeRange);
        
        Customer.Occupation occupation= (Customer.Occupation) occupationJComboBox.getSelectedItem();
        customer.setOccupation(occupation);
        
        customer.setCustomerEmail(emailJTextField.getText());
        customer.setPhoneNumber(phoneNumberJTextField.getText());
        
        updateJButton.setEnabled(true);
        saveJButton.setEnabled(false);
        
        JOptionPane.showMessageDialog(this, "Customer Details Updated.", "Update", JOptionPane.INFORMATION_MESSAGE);
        System.out.println("Customer info updated");
        customerNameJTextField.setEnabled(false);
        addressJTextField.setEnabled(false);
        cityJTextField.setEnabled(false);
        stateJTextField.setEnabled(false);
        countryJTextField.setEnabled(false);
        zipJTextField.setEnabled(false);
        genderJComboBox.setEnabled(false);
        ageRangeJComboBox.setEnabled(false);
        incomeRangeJComboBox.setEnabled(false);
        occupationJComboBox.setEnabled(false);
        emailJTextField.setEnabled(false);
        phoneNumberJTextField.setEnabled(false);
    }//GEN-LAST:event_saveJButtonActionPerformed
    
    private Boolean validateFields()
    {
        if(genderJComboBox.getSelectedIndex()==-1
            || occupationJComboBox.getSelectedIndex()==-1
                || incomeRangeJComboBox.getSelectedIndex()==-1
                || ageRangeJComboBox.getSelectedIndex()==-1
                || customerNameJTextField.getText().length()==0
                || addressJTextField.getText().length()==0
                || cityJTextField.getText().length()==0
                || stateJTextField.getText().length()==0
                || countryJTextField.getText().length()==0
                || zipJTextField.getText().length()==0
                || emailJTextField.getText().length()==0
                || phoneNumberJTextField.getText().length()==0)
        {
            return false;
        }
        return true;
    }
     
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JComboBox ageRangeJComboBox;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField cityJTextField;
    private javax.swing.JTextField countryJTextField;
    private javax.swing.JTextField customerIDJTextField;
    private javax.swing.JTextField customerNameJTextField;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JComboBox genderJComboBox;
    private javax.swing.JComboBox incomeRangeJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox occupationJComboBox;
    private javax.swing.JTextField phoneNumberJTextField;
    private javax.swing.JButton saveJButton;
    private javax.swing.JTextField stateJTextField;
    private javax.swing.JButton updateJButton;
    private javax.swing.JTextField zipJTextField;
    // End of variables declaration//GEN-END:variables
}
