/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Publisher.AccountManagerRole;

import Business.Enterprise.PublisherEnterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Sonam
 */
public class PublisherAccountManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountManagerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private PublisherEnterprise publisherEnterprise;
    private Organization organization;
    private UserAccount userAccount;
    public PublisherAccountManagerWorkAreaJPanel(JPanel userProcessContainer,PublisherEnterprise publisherEnterprise,Organization organization,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.publisherEnterprise=publisherEnterprise;
        this.organization=organization;
        this.userAccount=userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        managePaymentRequestsJButton = new javax.swing.JButton();
        myWorkRequestsJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Publisher Account Manager Work Area");

        managePaymentRequestsJButton.setText("Manage Post Payment Requests");
        managePaymentRequestsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePaymentRequestsJButtonActionPerformed(evt);
            }
        });

        myWorkRequestsJButton.setText("My Work Requests");
        myWorkRequestsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myWorkRequestsJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(myWorkRequestsJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(managePaymentRequestsJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(managePaymentRequestsJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(myWorkRequestsJButton)
                .addContainerGap(279, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void managePaymentRequestsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePaymentRequestsJButtonActionPerformed
        // TODO add your handling code here:
        ManagePostPaymentRequestsJPanel mpprjp = new ManagePostPaymentRequestsJPanel(userProcessContainer,publisherEnterprise, organization, userAccount);
        userProcessContainer.add("ManagePostPaymentRequestsJPanel", mpprjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePaymentRequestsJButtonActionPerformed

    private void myWorkRequestsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myWorkRequestsJButtonActionPerformed
        // TODO add your handling code here:
        PublisherAccountManagerRequestsJPanel pamrjp = new PublisherAccountManagerRequestsJPanel(userProcessContainer,publisherEnterprise, organization, userAccount);
        userProcessContainer.add("PublisherAccountManagerRequestsJPanel", pamrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_myWorkRequestsJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton managePaymentRequestsJButton;
    private javax.swing.JButton myWorkRequestsJButton;
    // End of variables declaration//GEN-END:variables
}
