/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Publisher.AccountManagerRole;

import Business.Enterprise.PublisherEnterprise;
import Business.Organization.Organization;
import Business.Publisher.WorkRequests.RequestPaymentWorkRequest;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sonam
 */
public class PublisherAccountManagerRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PublisherAccountManagerRequestsJPanel
     */
    private JPanel userProcessContainer;
    private PublisherEnterprise publisherEnterprise;
    private Organization organization;
    private UserAccount userAccount;
    public PublisherAccountManagerRequestsJPanel(JPanel userProcessContainer,PublisherEnterprise publisherEnterprise,Organization organization,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.publisherEnterprise=publisherEnterprise;
        this.organization=organization;
        this.userAccount=userAccount;
        populateMyRequestsTable();
    }
    private void populateMyRequestsTable()
    {
        DefaultTableModel dtm= (DefaultTableModel) myPaymentRequestsJTable.getModel();
        dtm.setRowCount(0);

        for (WorkRequest r : userAccount.getWorkQueue().getWorkRequestList()) {
            if (r instanceof RequestPaymentWorkRequest) {
                RequestPaymentWorkRequest request=(RequestPaymentWorkRequest)r;
                
                Object row[] = new Object[9];
                row[0] = request;
                row[1] = request.getAdSpace().getTitle();
                row[2] = request.getAdName();
                row[3] = request.getAmount();
                row[4] = request.getSender();
                row[5] = request.getReceiver() == null ? null : request.getReceiver().getPerson().getName();
                row[6] = request.getStatus();
                row[7] = request.getRequestDate();
                row[8] = request.getResolveDate();
                dtm.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myPaymentRequestsJTable = new javax.swing.JTable();
        backJButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        jLabel1.setText("My Payment Requests:");

        myPaymentRequestsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Ad Space", "Advertisement", "Amount", "Sender", "Receiver", "Status", "Request Date", "Resolve Date"
            }
        ));
        jScrollPane1.setViewportView(myPaymentRequestsJTable);

        backJButton2.setText("<<Back");
        backJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton2ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Publisher Account Manager Requests");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton2))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backJButton2)
                .addContainerGap(274, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable myPaymentRequestsJTable;
    // End of variables declaration//GEN-END:variables
}
