/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Advertiser.AdInventoryManagerRole;

import Business.Advertiser.Advertisement.Advertisement;
import Business.Advertiser.Organizations.AdCreatorOrganization;
import Business.Enterprise.AdvertiserEnterprise;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Advertiser.WorkRequests.AdCreationWorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sonam
 */
public class RequestAdvertisementsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestAdvertisementsJPanel
     */
    private JPanel userProcessContainer;
    private AdvertiserEnterprise adEnterprise;
    private UserAccount userAccount;
    public RequestAdvertisementsJPanel(JPanel userProcessContainer,Enterprise enterprise,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.adEnterprise= (AdvertiserEnterprise)enterprise;
        this.userAccount=userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        notesJTextField = new javax.swing.JTextField();
        backJButton1 = new javax.swing.JButton();
        requestAdJButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setText("Notes:");

        backJButton1.setText("<<Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });

        requestAdJButton.setText("Request Advertisement");
        requestAdJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestAdJButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Request Advertisement");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backJButton1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(requestAdJButton))))
                .addContainerGap(419, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(notesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton1)
                    .addComponent(requestAdJButton))
                .addContainerGap(497, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void requestAdJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestAdJButtonActionPerformed
        // TODO add your handling code here:
        
        Organization organization=null;
        for(Organization org:adEnterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(org instanceof AdCreatorOrganization)
            {
                organization=org;
                break;
            }
        }
        
        //Create blank ad;
        Advertisement advertisement= adEnterprise.getAdInventory().createAndAddAdvertisement();
        advertisement.setEnterprice(adEnterprise);
        advertisement.setNotes(notesJTextField.getText());
        
        //Create Ad creation request
        AdCreationWorkRequest myWorkRequest= new AdCreationWorkRequest();
        myWorkRequest.setSender(userAccount);
        myWorkRequest.setRequestDate(new Date());
        myWorkRequest.setMessage(notesJTextField.getText());
        myWorkRequest.setStatus("Sent");
        myWorkRequest.setAdvertisement(advertisement);
        
        if (organization!=null){
            organization.getWorkQueue().getWorkRequestList().add(myWorkRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(myWorkRequest);
        }
        System.out.println("Work request created and added to "+organization.getName()+" organization and "+userAccount.getUsername()+" Work queues");
        
        JOptionPane.showMessageDialog(this, "Advertisment request sent","Update",JOptionPane.INFORMATION_MESSAGE);
        notesJTextField.setText("");
    }//GEN-LAST:event_requestAdJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField notesJTextField;
    private javax.swing.JButton requestAdJButton;
    // End of variables declaration//GEN-END:variables
}
