/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Advertiser.AdInventoryManagerRole;

import Business.Advertiser.Advertisement.Advertisement;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Advertiser.WorkRequests.AdCreationWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sonam
 */
public class ViewAdInventoryManagerRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAdInventoryManagerRequestsJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    private UserAccount userAccount;
    public ViewAdInventoryManagerRequestsJPanel(JPanel userProcessContainer,Organization organization,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.organization=organization;
        this.userAccount=userAccount;
        populateMyRequestsTable();
    }
    private void populateMyRequestsTable()
    {
        DefaultTableModel dtm= (DefaultTableModel) myAdRequestsTable.getModel();
        dtm.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            if (request instanceof AdCreationWorkRequest) {
                Object row[] = new Object[9];

                row[0] = request;
                row[1] = request.getSender();
                row[2] = request.getReceiver() == null ? null : request.getReceiver().getPerson().getName();
                row[3] = request.getStatus();
                row[4] = request.getRequestDate();
                row[5] = request.getResolveDate();
                row[6] = ((AdCreationWorkRequest)request).getAdvertisement();
                row[7] = ((AdCreationWorkRequest)request).getAdvertisement().isReady()== Boolean.TRUE? "Yes":"No";
                row[8] = ((AdCreationWorkRequest)request).getAdvertisement().isEnabled()== Boolean.TRUE? "Yes":"No";
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myAdRequestsTable = new javax.swing.JTable();
        viewAdJButton = new javax.swing.JButton();
        backJButton1 = new javax.swing.JButton();
        markAdReadyJButton = new javax.swing.JButton();
        markAdEnabledJButton = new javax.swing.JButton();
        viewAdJButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("My Ad Requests:");

        myAdRequestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status", "Request Date", "Resolve Date", "Advertisement", "Ready?", "Enabled?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(myAdRequestsTable);

        viewAdJButton.setText("View Advertisement");
        viewAdJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAdJButtonActionPerformed(evt);
            }
        });

        backJButton1.setText("<<Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });

        markAdReadyJButton.setText("Mark Ready");
        markAdReadyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markAdReadyJButtonActionPerformed(evt);
            }
        });

        markAdEnabledJButton.setText("Mark Enabled");
        markAdEnabledJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markAdEnabledJButtonActionPerformed(evt);
            }
        });

        viewAdJButton1.setText("View/Edit Ad Detils");
        viewAdJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAdJButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ad Inventory Manager Requests");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(backJButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewAdJButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(markAdReadyJButton)
                        .addGap(18, 18, 18)
                        .addComponent(markAdEnabledJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewAdJButton)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton1)
                    .addComponent(viewAdJButton)
                    .addComponent(markAdReadyJButton)
                    .addComponent(markAdEnabledJButton)
                    .addComponent(viewAdJButton1))
                .addContainerGap(492, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void markAdReadyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markAdReadyJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = myAdRequestsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Work Request.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        AdCreationWorkRequest myWorkRequest = (AdCreationWorkRequest) myAdRequestsTable.getValueAt(selectedRow, 0);
        
        Advertisement advertisement= myWorkRequest.getAdvertisement();
        
        if(advertisement.isReady())
        {
            JOptionPane.showMessageDialog(this,"Advertise is already marked Ready","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!(myWorkRequest.getStatus().equals("Completed")))
        {
            JOptionPane.showMessageDialog(this,"Advertisement is not ready yet","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        advertisement.setReady(true);
        System.out.println("Advertisement marked ready");
        populateMyRequestsTable();
    }//GEN-LAST:event_markAdReadyJButtonActionPerformed

    private void markAdEnabledJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markAdEnabledJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = myAdRequestsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Work Request.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        AdCreationWorkRequest myWorkRequest = (AdCreationWorkRequest) myAdRequestsTable.getValueAt(selectedRow, 0);
        
        Advertisement advertisement= myWorkRequest.getAdvertisement();
        
        if(advertisement.isEnabled())
        {
            JOptionPane.showMessageDialog(this,"Advertise is already marked Enabled","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!(myWorkRequest.getStatus().equals("Completed")))
        {
            JOptionPane.showMessageDialog(this,"Advertisement is not ready yet","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!advertisement.isReady() && (myWorkRequest.getStatus().equals("Completed")))
        {
            JOptionPane.showMessageDialog(this,"Please mark advertise as Ready first.","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        advertisement.setEnabled(true);
        System.out.println("Advertisement marked enabled");
        populateMyRequestsTable();
    }//GEN-LAST:event_markAdEnabledJButtonActionPerformed

    private void viewAdJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAdJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = myAdRequestsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Work Request.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        AdCreationWorkRequest myWorkRequest = (AdCreationWorkRequest) myAdRequestsTable.getValueAt(selectedRow, 0);
        if(!myWorkRequest.getStatus().equals("Completed"))
        {
            JOptionPane.showMessageDialog(this, "Advertisement not ready yet.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Advertisement advertisement= myWorkRequest.getAdvertisement();
        
        ViewAdvertisementJPanel vijp = new ViewAdvertisementJPanel(userProcessContainer,advertisement);
        userProcessContainer.add("ViewImageJPanel", vijp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewAdJButtonActionPerformed

    private void viewAdJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAdJButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = myAdRequestsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Work Request.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        AdCreationWorkRequest myWorkRequest = (AdCreationWorkRequest) myAdRequestsTable.getValueAt(selectedRow, 0);
        if(!myWorkRequest.getStatus().equals("Completed"))
        {
            JOptionPane.showMessageDialog(this, "Advertisement not ready yet.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Advertisement advertisement= myWorkRequest.getAdvertisement();

        ViewEditAdDetailsJPanel vadjp = new ViewEditAdDetailsJPanel(userProcessContainer,advertisement);
        userProcessContainer.add("ViewAdvertisementDetailsJPanel", vadjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewAdJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton markAdEnabledJButton;
    private javax.swing.JButton markAdReadyJButton;
    private javax.swing.JTable myAdRequestsTable;
    private javax.swing.JButton viewAdJButton;
    private javax.swing.JButton viewAdJButton1;
    // End of variables declaration//GEN-END:variables
}
