/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Advertiser.AdInventoryManagerRole;

import Business.Advertiser.Advertisement.Advertisement;
import Business.Utils.MyIntegerVerifier;
import Business.Utils.MyStringVerifier;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sonam
 */
public class ViewEditAdDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewImageAdvertisementJPanel
     */
    private JPanel userProcessContainer;
    private Advertisement advertisement;
    public ViewEditAdDetailsJPanel(JPanel userProcessContainer,Advertisement advertisement) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.advertisement=advertisement;
        setVerifiers();
        DisplayAdDetails();
    }
    private void setVerifiers()
    {
        MyStringVerifier myStringVerifier= new MyStringVerifier();
        titleJTextField.setInputVerifier(myStringVerifier);
        MyIntegerVerifier myIntegerVerifier= new MyIntegerVerifier();
        widthJTextField.setInputVerifier(myIntegerVerifier);
        heightJTextField.setInputVerifier(myIntegerVerifier);
    }
    private void DisplayAdDetails()
    {
        advertisementIDJTextField.setText(String.valueOf(advertisement.getAdvertisementID()));
        titleJTextField.setText(advertisement.getTitle());
        widthJTextField.setText(String.valueOf(advertisement.getWidth()));
        heightJTextField.setText(String.valueOf(advertisement.getHeight()));
        locationJTextField.setText(advertisement.getLocation());
        dateCreatedJTextField.setText(advertisement.getDateCreated().toString());
        if(advertisement.isReady())
        {
            isReadyYesJRadioButton.setSelected(true);
            isReadyNoJRadioButton.setSelected(false);
        }
        else
        {
            isReadyYesJRadioButton.setSelected(false);
            isReadyNoJRadioButton.setSelected(true);
        }
        
        if(advertisement.isEnabled())
        {
            isEnabledYesJRadioButton.setSelected(true);
            isEnabledNoJRadioButton.setSelected(false);
        }
        else
        {
            isEnabledYesJRadioButton.setSelected(false);
            isEnabledNoJRadioButton.setSelected(true);
        }
        notesJTextField.setText(advertisement.getNotes());
        adWordsJTextField.setText(advertisement.getAdWords());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        advertisementIDJTextField = new javax.swing.JTextField();
        titleJTextField = new javax.swing.JTextField();
        widthJTextField = new javax.swing.JTextField();
        heightJTextField = new javax.swing.JTextField();
        locationJTextField = new javax.swing.JTextField();
        dateCreatedJTextField = new javax.swing.JTextField();
        notesJTextField = new javax.swing.JTextField();
        adWordsJTextField = new javax.swing.JTextField();
        isReadyNoJRadioButton = new javax.swing.JRadioButton();
        isReadyYesJRadioButton = new javax.swing.JRadioButton();
        isEnabledYesJRadioButton = new javax.swing.JRadioButton();
        isEnabledNoJRadioButton = new javax.swing.JRadioButton();
        backJButton1 = new javax.swing.JButton();
        updateJButton = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jLabel1.setText("Advertisement ID:");

        jLabel2.setText("Title:");

        jLabel4.setText("Width:");

        jLabel5.setText("Height:");

        jLabel6.setText("Location:");

        jLabel7.setText("Date Created:");

        jLabel8.setText("Ready?:");

        jLabel9.setText("Enabled?:");

        jLabel10.setText("Notes:");

        jLabel11.setText("Ad Words:");

        advertisementIDJTextField.setEnabled(false);

        titleJTextField.setEnabled(false);

        widthJTextField.setEnabled(false);

        heightJTextField.setEnabled(false);

        locationJTextField.setEnabled(false);

        dateCreatedJTextField.setEnabled(false);

        notesJTextField.setEnabled(false);

        adWordsJTextField.setEnabled(false);

        isReadyNoJRadioButton.setText("No");
        isReadyNoJRadioButton.setEnabled(false);

        isReadyYesJRadioButton.setSelected(true);
        isReadyYesJRadioButton.setText("Yes");
        isReadyYesJRadioButton.setEnabled(false);

        isEnabledYesJRadioButton.setSelected(true);
        isEnabledYesJRadioButton.setText("Yes");
        isEnabledYesJRadioButton.setEnabled(false);

        isEnabledNoJRadioButton.setText("No");
        isEnabledNoJRadioButton.setEnabled(false);

        backJButton1.setText("<<Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });

        updateJButton.setText("Update");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });

        saveJButton.setText("Save");
        saveJButton.setEnabled(false);
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("View/Edit Advertisement Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adWordsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(notesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateCreatedJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locationJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(isReadyYesJRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(isReadyNoJRadioButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(isEnabledYesJRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(isEnabledNoJRadioButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heightJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(widthJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(advertisementIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(667, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(advertisementIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(titleJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(widthJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(heightJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(locationJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dateCreatedJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(isReadyYesJRadioButton)
                        .addComponent(isReadyNoJRadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(isEnabledYesJRadioButton)
                    .addComponent(isEnabledNoJRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(notesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(adWordsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton1)
                    .addComponent(updateJButton)
                    .addComponent(saveJButton))
                .addContainerGap(224, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
        // TODO add your handling code here:
        titleJTextField.setEnabled(true);
        heightJTextField.setEnabled(true);
        widthJTextField.setEnabled(true);
        isReadyYesJRadioButton.setEnabled(true);
        isReadyNoJRadioButton.setEnabled(true);
        isEnabledYesJRadioButton.setEnabled(true);
        isEnabledNoJRadioButton.setEnabled(true);
        adWordsJTextField.setEnabled(true);
        notesJTextField.setEnabled(true);
        updateJButton.setEnabled(false);
        saveJButton.setEnabled(true);
    }//GEN-LAST:event_updateJButtonActionPerformed

    private Boolean verifyFields()
    {
        if(titleJTextField.getText().length()==0
            || heightJTextField.getText().length()==0
            || widthJTextField.getText().length()==0
            || adWordsJTextField.getText().length()==0)
        {
            return false;
        }
        return true;
    }
    
    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:
        if(!verifyFields())
        {
            JOptionPane.showMessageDialog(this,"Please enter valid inputs","Update",JOptionPane.ERROR_MESSAGE);
            return;
        }
        advertisement.setTitle(titleJTextField.getText());
        advertisement.setWidth(Integer.parseInt(widthJTextField.getText()));
        advertisement.setHeight(Integer.parseInt(heightJTextField.getText()));
        if(isReadyYesJRadioButton.isSelected())
        {
            advertisement.setReady(true);
        }
        else if(isReadyNoJRadioButton.isSelected())
        {
            advertisement.setReady(false);
        }
        
        if(isEnabledYesJRadioButton.isSelected())
        {
            advertisement.setEnabled(true);
        }
        else if(isEnabledNoJRadioButton.isSelected())
        {
            advertisement.setEnabled(false);
        }
        advertisement.setAdWords(adWordsJTextField.getText());
        advertisement.setNotes(notesJTextField.getText());
        System.out.println("Advertisement updated");
        JOptionPane.showMessageDialog(this,"Advertisement updated!!","Update",JOptionPane.INFORMATION_MESSAGE);
        saveJButton.setEnabled(false);
        updateJButton.setEnabled(true);
        titleJTextField.setEnabled(false);
        heightJTextField.setEnabled(false);
        widthJTextField.setEnabled(false);
        isReadyYesJRadioButton.setEnabled(false);
        isReadyNoJRadioButton.setEnabled(false);
        isEnabledYesJRadioButton.setEnabled(false);
        isEnabledNoJRadioButton.setEnabled(false);
        adWordsJTextField.setEnabled(false);
        notesJTextField.setEnabled(false);
    }//GEN-LAST:event_saveJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adWordsJTextField;
    private javax.swing.JTextField advertisementIDJTextField;
    private javax.swing.JButton backJButton1;
    private javax.swing.JTextField dateCreatedJTextField;
    private javax.swing.JTextField heightJTextField;
    private javax.swing.JRadioButton isEnabledNoJRadioButton;
    private javax.swing.JRadioButton isEnabledYesJRadioButton;
    private javax.swing.JRadioButton isReadyNoJRadioButton;
    private javax.swing.JRadioButton isReadyYesJRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField locationJTextField;
    private javax.swing.JTextField notesJTextField;
    private javax.swing.JButton saveJButton;
    private javax.swing.JTextField titleJTextField;
    private javax.swing.JButton updateJButton;
    private javax.swing.JTextField widthJTextField;
    // End of variables declaration//GEN-END:variables
}
