/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Supplier.ShippingSpecialist;

import Business.Order.Order;
import Business.Organization.Organization;
import Business.Supplier.WorkRequests.ShippingRequest;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import UserInterface.Supplier.SalesRepresentative.ViewCustomerOrderDetailsJPanel;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sonam
 */
public class ManageShippingRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageShippingRequestsJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    private UserAccount ua;

    public ManageShippingRequestsJPanel(JPanel userProcessContainer, Organization organization, UserAccount ua) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.ua = ua;
        populateRequestTable();
        populateMyRequestTable();
    }

    private void populateRequestTable() {
        DefaultTableModel dtm = (DefaultTableModel) orgShippingRequestsTable.getModel();
        dtm.setRowCount(0);

        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof ShippingRequest) {
                Object row[] = new Object[7];

                row[0] = request;
                row[1] = ((ShippingRequest) request).getOrder();
                row[2] = request.getSender();
                row[3] = request.getReceiver() == null ? null : request.getReceiver().getPerson().getName();
                row[4] = request.getStatus();
                row[5] = request.getRequestDate();
                row[6] = request.getResolveDate();
                dtm.addRow(row);
            }
        }

    }

    private void populateMyRequestTable() {
        DefaultTableModel dtm = (DefaultTableModel) myShippingRequestsJTable.getModel();
        dtm.setRowCount(0);

        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof ShippingRequest) {
                if (request.getReceiver() == ua) {
                    Object row[] = new Object[7];
                    row[0] = request;
                    row[1] = ((ShippingRequest) request).getOrder();
                    row[2] = request.getSender();
                    row[3] = request.getReceiver() == null ? null : request.getReceiver().getPerson().getName();
                    row[4] = request.getStatus();
                    row[5] = request.getRequestDate();
                    row[6] = request.getResolveDate();
                    dtm.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orgShippingRequestsTable = new javax.swing.JTable();
        refreshJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        assignToMeJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        myShippingRequestsJTable = new javax.swing.JTable();
        preShippingStatusJButton = new javax.swing.JButton();
        readyForShippingStatusJButton = new javax.swing.JButton();
        markAsShippedJButton = new javax.swing.JButton();
        viewOrderDetaisJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Shipping Specialist Work Area");

        orgShippingRequestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Order ID", "Sender", "Receiver", "Status", "Request Date", "Resolve Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orgShippingRequestsTable);

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        assignToMeJButton.setText("Assign To Me");
        assignToMeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignToMeJButtonActionPerformed(evt);
            }
        });

        myShippingRequestsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Order ID", "Sender", "Receiver", "Status", "Request Date", "Resolve Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(myShippingRequestsJTable);

        preShippingStatusJButton.setText("Pre-Shipping");
        preShippingStatusJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preShippingStatusJButtonActionPerformed(evt);
            }
        });

        readyForShippingStatusJButton.setText("Ready For Shipping");
        readyForShippingStatusJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readyForShippingStatusJButtonActionPerformed(evt);
            }
        });

        markAsShippedJButton.setText("Mark As Shipped");
        markAsShippedJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markAsShippedJButtonActionPerformed(evt);
            }
        });

        viewOrderDetaisJButton.setText("View Order");
        viewOrderDetaisJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderDetaisJButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Organization Shipping Requests:");

        jLabel3.setText("My Shipping Requests:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                        .addComponent(refreshJButton)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backJButton)
                            .addGap(18, 18, 18)
                            .addComponent(viewOrderDetaisJButton)
                            .addGap(18, 18, 18)
                            .addComponent(assignToMeJButton))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(preShippingStatusJButton)
                            .addGap(18, 18, 18)
                            .addComponent(readyForShippingStatusJButton)
                            .addGap(18, 18, 18)
                            .addComponent(markAsShippedJButton))
                        .addComponent(jScrollPane2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(340, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(assignToMeJButton)
                    .addComponent(viewOrderDetaisJButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preShippingStatusJButton)
                    .addComponent(readyForShippingStatusJButton)
                    .addComponent(markAsShippedJButton))
                .addContainerGap(264, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void preShippingStatusJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preShippingStatusJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = myShippingRequestsJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Work Request.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ShippingRequest myWorkRequest = (ShippingRequest) myShippingRequestsJTable.getValueAt(selectedRow, 0);
        if (myWorkRequest.isHasProcessed()) {
            JOptionPane.showMessageDialog(this, "Cannot alter request as already processed.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        myWorkRequest.setStatus("Pre-Shipping");
        myWorkRequest.getOrder().setStatus("Pre-Shipping");
        myWorkRequest.getOrder().setStatusBy(new Date());
        myWorkRequest.setResolveDate(new Date());
        System.out.println("Status updated to Pre-Shipping");
        populateRequestTable();
        populateMyRequestTable();
    }//GEN-LAST:event_preShippingStatusJButtonActionPerformed

    private void readyForShippingStatusJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readyForShippingStatusJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = myShippingRequestsJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Work Request.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ShippingRequest myWorkRequest = (ShippingRequest) myShippingRequestsJTable.getValueAt(selectedRow, 0);
        if (myWorkRequest.isHasProcessed()) {
            JOptionPane.showMessageDialog(this, "Cannot alter request as already processed.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        myWorkRequest.setStatus("Ready To Ship");
        myWorkRequest.getOrder().setStatus("Ready To Ship");
        myWorkRequest.getOrder().setStatusBy(new Date());
        myWorkRequest.setResolveDate(new Date());
        System.out.println("Status updated as Ready to Ship");
        populateRequestTable();
        populateMyRequestTable();
    }//GEN-LAST:event_readyForShippingStatusJButtonActionPerformed

    private void markAsShippedJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markAsShippedJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = myShippingRequestsJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Work Request.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ShippingRequest myWorkRequest = (ShippingRequest) myShippingRequestsJTable.getValueAt(selectedRow, 0);
        if (myWorkRequest.isHasProcessed()) {
            JOptionPane.showMessageDialog(this, "Cannot alter request as already processed.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        myWorkRequest.setStatus("Shipped");
        myWorkRequest.getOrder().setStatus("Shipped");
        myWorkRequest.getOrder().setStatusBy(new Date());
        myWorkRequest.setResolveDate(new Date());
        myWorkRequest.setHasProcessed(true);
        System.out.println("Order marked as Shipped");
        populateRequestTable();
        populateMyRequestTable();
    }//GEN-LAST:event_markAsShippedJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        populateRequestTable();
        populateMyRequestTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void assignToMeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignToMeJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = orgShippingRequestsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Work Request.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        WorkRequest myWorkRequest = (WorkRequest) orgShippingRequestsTable.getValueAt(selectedRow, 0);
        if(myWorkRequest.getReceiver()!=null)
        {
            JOptionPane.showMessageDialog(this, "Request is already assigned to "+myWorkRequest.getReceiver().getPerson().getName(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        myWorkRequest.setReceiver(ua);
        myWorkRequest.setStatus("Under Review");
        myWorkRequest.setResolveDate(new Date());
        System.out.println("Request assigned to "+ua.getUsername());
        populateRequestTable();
        populateMyRequestTable();
    }//GEN-LAST:event_assignToMeJButtonActionPerformed

    private void viewOrderDetaisJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderDetaisJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = orgShippingRequestsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Work Request.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Order order = (Order) orgShippingRequestsTable.getValueAt(selectedRow, 1);

        ViewCustomerOrderDetailsJPanel vcodjp = new ViewCustomerOrderDetailsJPanel(userProcessContainer, order);
        userProcessContainer.add("ViewCustomerOrderDetailsJPanel", vcodjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewOrderDetaisJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignToMeJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton markAsShippedJButton;
    private javax.swing.JTable myShippingRequestsJTable;
    private javax.swing.JTable orgShippingRequestsTable;
    private javax.swing.JButton preShippingStatusJButton;
    private javax.swing.JButton readyForShippingStatusJButton;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton viewOrderDetaisJButton;
    // End of variables declaration//GEN-END:variables
}
