/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Advertiser.DSPManagerRole;

import Business.Advertiser.DemandSidePlatform.DSP;
import Business.Customer.Customer;
import Business.Utils.MyDoubleVerifier;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sonam
 */
public class EditDSPJPanel extends javax.swing.JPanel {

    /**
     * Creates new form addDSPJPanel
     */
    private JPanel userProcessContainer;
    private DSP dsp;

    public EditDSPJPanel(JPanel userProcessContainer, DSP dsp) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.dsp = dsp;
        setVerifiers();
        populateComboboxes();
        populateDSPdata();
    }
    
    private void setVerifiers()
    {
        MyDoubleVerifier myDoubleVerifier= new MyDoubleVerifier();
        costByClickJTextField.setInputVerifier(myDoubleVerifier);
    }

    private void populateComboboxes() {
        genderJComboBox.removeAllItems();;
        ageRangeJComboBox.removeAllItems();
        incomeRangeJComboBox.removeAllItems();;
        occupationJComboBox.removeAllItems();

        for (Customer.Gender gender : Customer.Gender.values()) {
            genderJComboBox.addItem(gender);
        }

        for (Customer.AgeRange ageRange : Customer.AgeRange.values()) {
            ageRangeJComboBox.addItem(ageRange);
        }

        for (Customer.IncomeRange incomeRange : Customer.IncomeRange.values()) {
            incomeRangeJComboBox.addItem(incomeRange);
        }

        for (Customer.Occupation occupation : Customer.Occupation.values()) {
            occupationJComboBox.addItem(occupation);
        }
    }
    
    private void populateDSPdata()
    {
        dspIDJTextField.setText(String.valueOf(dsp.getDspId()));
        genderJComboBox.setSelectedItem(dsp.getGender());
        ageRangeJComboBox.setSelectedItem(dsp.getAgeRange());
        incomeRangeJComboBox.setSelectedItem(dsp.getIncomeRange());
        occupationJComboBox.setSelectedItem(dsp.getOccupation());
        costByClickJTextField.setText(String.valueOf(dsp.getCostPerClick()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        genderJComboBox = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        ageRangeJComboBox = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        occupationJComboBox = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        incomeRangeJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        costByClickJTextField = new javax.swing.JTextField();
        backJButton1 = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        dspIDJTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        jLabel12.setText("Gender:");

        jLabel13.setText("Age Range:");

        jLabel14.setText("Occupation:");

        jLabel15.setText("Income Range:");

        jLabel1.setText("Cost Per Click:");

        backJButton1.setText("<<Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });

        saveJButton.setText("Save");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("DSP ID:");

        dspIDJTextField.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Edit DSP Rule");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(backJButton1)
                            .addComponent(jLabel2))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(saveJButton)
                            .addComponent(ageRangeJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(genderJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(occupationJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(incomeRangeJComboBox, 0, 150, Short.MAX_VALUE)
                            .addComponent(costByClickJTextField)
                            .addComponent(dspIDJTextField)))
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(671, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dspIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(genderJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ageRangeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(occupationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(incomeRangeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(costByClickJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton1)
                    .addComponent(saveJButton))
                .addContainerGap(369, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:

        if(!validateFields())
        {
            JOptionPane.showMessageDialog(this,"Please enter correct values","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Customer.Gender gender = (Customer.Gender) genderJComboBox.getSelectedItem();
        dsp.setGender(gender);

        Customer.AgeRange ageRange = (Customer.AgeRange) ageRangeJComboBox.getSelectedItem();
        dsp.setAgeRange(ageRange);

        Customer.IncomeRange incomeRange = (Customer.IncomeRange) incomeRangeJComboBox.getSelectedItem();
        dsp.setIncomeRange(incomeRange);

        Customer.Occupation occupation = (Customer.Occupation) occupationJComboBox.getSelectedItem();
        dsp.setOccupation(occupation);
        
        dsp.setCostPerClick(Double.parseDouble(costByClickJTextField.getText()));
        System.out.println("DSP updated");
        JOptionPane.showMessageDialog(this, "DSP updated!!", "Update", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_saveJButtonActionPerformed

     private Boolean validateFields()
    {
        if(genderJComboBox.getSelectedIndex()==-1
            || occupationJComboBox.getSelectedIndex()==-1
                || incomeRangeJComboBox.getSelectedIndex()==-1
                || ageRangeJComboBox.getSelectedIndex()==-1
                || costByClickJTextField.getText().length()==0)
        {
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ageRangeJComboBox;
    private javax.swing.JButton backJButton1;
    private javax.swing.JTextField costByClickJTextField;
    private javax.swing.JTextField dspIDJTextField;
    private javax.swing.JComboBox genderJComboBox;
    private javax.swing.JComboBox incomeRangeJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox occupationJComboBox;
    private javax.swing.JButton saveJButton;
    // End of variables declaration//GEN-END:variables
}
