/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Publisher.AdSpaceManagerRole;

import UserInterface.Advertiser.AdInventoryManagerRole.*;
import Business.Enterprise.Enterprise;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Sonam
 */
public class AdSpaceManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdInventoryManagerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private OrganizationDirectory organizationDirectory;
    private UserAccount userAccount;
    public AdSpaceManagerWorkAreaJPanel(JPanel userProcessContainer,Enterprise enterprise, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.organizationDirectory=enterprise.getOrganizationDirectory();
        this.userAccount=userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        requestAdSpaceJButton = new javax.swing.JButton();
        manageAdSpaceJButton = new javax.swing.JButton();
        myRequestsJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ad Space Manager Work Area");

        requestAdSpaceJButton.setText("Request Ad Space");
        requestAdSpaceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestAdSpaceJButtonActionPerformed(evt);
            }
        });

        manageAdSpaceJButton.setText("Manage Ad Space");
        manageAdSpaceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdSpaceJButtonActionPerformed(evt);
            }
        });

        myRequestsJButton.setText("My Requests");
        myRequestsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myRequestsJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(myRequestsJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manageAdSpaceJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(requestAdSpaceJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(488, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageAdSpaceJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(requestAdSpaceJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(myRequestsJButton)
                .addContainerGap(410, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestAdSpaceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestAdSpaceJButtonActionPerformed
        // TODO add your handling code here:
        RequestAdSpaceJPanel rasjp = new RequestAdSpaceJPanel(userProcessContainer,enterprise,userAccount);
        userProcessContainer.add("RequestAdSpaceJPanel", rasjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestAdSpaceJButtonActionPerformed

    private void manageAdSpaceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdSpaceJButtonActionPerformed
        // TODO add your handling code here:
        ManageAdSpaceJPanel masjp = new ManageAdSpaceJPanel(userProcessContainer,enterprise,userAccount);
        userProcessContainer.add("ManageAdSpaceJPanel", masjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageAdSpaceJButtonActionPerformed

    private void myRequestsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myRequestsJButtonActionPerformed
        // TODO add your handling code here:
        ViewAdSpaceManagerRequestsJPanel vasmrjp = new ViewAdSpaceManagerRequestsJPanel(userProcessContainer,enterprise,userAccount);
        userProcessContainer.add("ViewAdSpaceManagerRequestsJPanel", vasmrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_myRequestsJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageAdSpaceJButton;
    private javax.swing.JButton myRequestsJButton;
    private javax.swing.JButton requestAdSpaceJButton;
    // End of variables declaration//GEN-END:variables
}
